// ============================================================
// MISAKA Network — Proof Backend Traits
// ============================================================
//
// Abstract interfaces for ZK proofs. Implementations can be
// swapped between testnet (fast, not ZK) and mainnet (lattice ZK).
//
// Backends:
//   TestnetBackend — hash-based stubs, fast, NOT zero-knowledge
//   LatticeBackend — real lattice ZK proofs (Phase 3, stubbed)
//
// The TX builder and verifier use these traits, never calling
// concrete proof functions directly.
//
// ============================================================

use crate::commitment::{CommitmentOpening, BalanceProof};
use serde::{Serialize, Deserialize};

#[derive(Debug, thiserror::Error)]
pub enum ProofError {
    #[error("Proof generation failed: {0}")]
    GenerationFailed(String),
    #[error("Proof verification failed")]
    VerificationFailed,
    #[error("Backend not available: {0}")]
    BackendUnavailable(String),
}

// ── Range proof ──

/// Serialized range proof (backend-agnostic).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RangeProofData {
    /// Backend identifier (for deserialization routing)
    pub backend_id: u8,
    /// The proof bytes (format depends on backend)
    pub proof: Vec<u8>,
}

/// Range proof backend: proves committed value ∈ [0, 2^64).
pub trait RangeProofBackend: Send + Sync {
    /// Backend identifier (must be unique per implementation).
    fn backend_id(&self) -> u8;

    /// Generate a range proof for a committed value.
    ///
    /// Proves: the value in `opening` is in [0, 2^64) without
    /// revealing the value itself.
    fn prove(&self, opening: &CommitmentOpening) -> Result<RangeProofData, ProofError>;

    /// Verify a range proof against a commitment hash.
    ///
    /// `commitment_hash`: the 32-byte on-chain commitment.
    /// `proof`: the proof data generated by `prove()`.
    fn verify(
        &self,
        commitment_hash: &[u8; 32],
        proof: &RangeProofData,
    ) -> Result<bool, ProofError>;
}

// ── Balance proof ──

/// Serialized balance proof (backend-agnostic).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BalanceProofData {
    pub backend_id: u8,
    pub proof: Vec<u8>,
}

/// Balance proof backend: proves Σ(inputs) = Σ(outputs) + fee.
pub trait BalanceProofBackend: Send + Sync {
    fn backend_id(&self) -> u8;

    /// Generate a balance proof.
    ///
    /// Proves: the sum of input commitment openings equals the sum
    /// of output commitment openings plus the fee, without revealing
    /// any individual values.
    fn prove(
        &self,
        inputs: &[CommitmentOpening],
        outputs: &[CommitmentOpening],
        fee: u64,
    ) -> Result<BalanceProofData, ProofError>;

    /// Verify a balance proof.
    ///
    /// The verifier has only the commitment hashes (on-chain data),
    /// not the openings.
    fn verify(&self, proof: &BalanceProofData) -> Result<bool, ProofError>;
}

// ════════════════════════════════════════════
// Testnet Backend (fast, NOT zero-knowledge)
// ════════════════════════════════════════════

/// Testnet proof backend.
///
/// Range proof: just hashes the commitment (no ZK property).
/// Balance proof: checks excess vector hash == zero hash.
///
/// This is fast but provides NO privacy for the proofs themselves.
/// The amounts are still hidden by Pedersen commitments; these proofs
/// just verify structural correctness.
///
/// Suitable for testnet where proof generation speed matters more
/// than formal ZK guarantees on the proofs.
pub struct TestnetBackend;

impl TestnetBackend {
    pub const BACKEND_ID: u8 = 0x01;
}

impl RangeProofBackend for TestnetBackend {
    fn backend_id(&self) -> u8 { Self::BACKEND_ID }

    fn prove(&self, opening: &CommitmentOpening) -> Result<RangeProofData, ProofError> {
        // Testnet: prove we know the opening (hash of value + blinding + commitment)
        use crate::hash::{Domain, domain_hash_multi};
        let proof = domain_hash_multi(
            Domain::Commitment,
            &[
                &opening.value.to_le_bytes(),
                &opening.blinding.to_le_bytes(),
                &opening.hash,
            ],
            32,
        );
        Ok(RangeProofData {
            backend_id: Self::BACKEND_ID,
            proof,
        })
    }

    fn verify(
        &self,
        commitment_hash: &[u8; 32],
        proof: &RangeProofData,
    ) -> Result<bool, ProofError> {
        // Testnet: we can't truly verify without the opening.
        // In testnet mode, range proofs are trusted if present and well-formed.
        // The balance proof catches any inflation regardless.
        Ok(proof.backend_id == Self::BACKEND_ID && proof.proof.len() == 32)
    }
}

impl BalanceProofBackend for TestnetBackend {
    fn backend_id(&self) -> u8 { Self::BACKEND_ID }

    fn prove(
        &self,
        inputs: &[CommitmentOpening],
        outputs: &[CommitmentOpening],
        fee: u64,
    ) -> Result<BalanceProofData, ProofError> {
        let bp = crate::commitment::create_balance_proof(inputs, outputs, fee);
        Ok(BalanceProofData {
            backend_id: Self::BACKEND_ID,
            proof: bp.excess_hash.to_vec(),
        })
    }

    fn verify(&self, proof: &BalanceProofData) -> Result<bool, ProofError> {
        if proof.backend_id != Self::BACKEND_ID || proof.proof.len() != 32 {
            return Ok(false);
        }
        let mut hash = [0u8; 32];
        hash.copy_from_slice(&proof.proof);
        let bp = BalanceProof { excess_hash: hash };
        Ok(crate::commitment::verify_balance_proof(&bp))
    }
}

// ════════════════════════════════════════════
// Lattice Backend (stub — Phase 3)
// ════════════════════════════════════════════

/// Lattice ZK proof backend (Phase 3).
///
/// Will implement:
///   Range: lattice-based bulletproof analog (Esgin et al.)
///   Balance: MLWE-based Σ-protocol for commitment arithmetic
///
/// Currently returns BackendUnavailable for all operations.
pub struct LatticeBackend;

impl LatticeBackend {
    pub const BACKEND_ID: u8 = 0x02;
}

impl RangeProofBackend for LatticeBackend {
    fn backend_id(&self) -> u8 { Self::BACKEND_ID }

    fn prove(&self, _opening: &CommitmentOpening) -> Result<RangeProofData, ProofError> {
        Err(ProofError::BackendUnavailable(
            "Lattice range proofs not yet implemented (Phase 3)".into()
        ))
    }

    fn verify(&self, _hash: &[u8; 32], _proof: &RangeProofData) -> Result<bool, ProofError> {
        Err(ProofError::BackendUnavailable(
            "Lattice range proofs not yet implemented (Phase 3)".into()
        ))
    }
}

impl BalanceProofBackend for LatticeBackend {
    fn backend_id(&self) -> u8 { Self::BACKEND_ID }

    fn prove(&self, _i: &[CommitmentOpening], _o: &[CommitmentOpening], _f: u64) -> Result<BalanceProofData, ProofError> {
        Err(ProofError::BackendUnavailable(
            "Lattice balance proofs not yet implemented (Phase 3)".into()
        ))
    }

    fn verify(&self, _proof: &BalanceProofData) -> Result<bool, ProofError> {
        Err(ProofError::BackendUnavailable(
            "Lattice balance proofs not yet implemented (Phase 3)".into()
        ))
    }
}

// ════════════════════════════════════════════
// Unified backend (prevents mismatched range/balance backends)
// ════════════════════════════════════════════

/// Combined proof backend.
///
/// A single type must implement BOTH range and balance proofs.
/// This makes it structurally impossible to use different backends
/// for range vs balance within the same transaction.
///
/// The builder and verifier accept `&impl ProofBackend`.
pub trait ProofBackend: RangeProofBackend + BalanceProofBackend {}

// Auto-implement for any type that has both traits
impl<T: RangeProofBackend + BalanceProofBackend> ProofBackend for T {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commitment;

    #[test]
    fn test_testnet_range_proof() {
        let backend = TestnetBackend;
        let opening = commitment::commit(42_000, 99);
        let proof = backend.prove(&opening).unwrap();
        assert_eq!(proof.backend_id, TestnetBackend::BACKEND_ID);
        assert!(backend.verify(&opening.hash, &proof).unwrap());
    }

    #[test]
    fn test_testnet_balance_proof() {
        let backend = TestnetBackend;
        let inp = commitment::commit(1000, 10);
        let out = commitment::commit(900, 10);
        let proof = backend.prove(&[inp], &[out], 100).unwrap();
        assert!(backend.verify(&proof).unwrap());
    }

    #[test]
    fn test_testnet_balance_unbalanced_fails() {
        let backend = TestnetBackend;
        let inp = commitment::commit(1000, 10);
        let out = commitment::commit(500, 10); // short 400
        let proof = backend.prove(&[inp], &[out], 100).unwrap();
        assert!(!backend.verify(&proof).unwrap());
    }

    #[test]
    fn test_lattice_backend_unavailable() {
        let backend = LatticeBackend;
        let opening = commitment::commit(100, 10);
        assert!(backend.prove(&opening).is_err());
    }
}
